name: Clippy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: install webkit2gtk
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - run: cargo clippy --all-targets --all-features -- -D warnings
